# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65248f4e998213b138914a4f8931ac08a4ada00683e043696eb68695000822268bf6cf591fb6c93fcaee29990b97208926bc6e503cb50dd4942aac5ea1f18468

test:
  secret_key_base: 0dfee9d85cae193970be7d138925aa2b9e07e568b3a8d7b31f70b60f62f48754b9cbb0a707537231ad78231dcf0c9d6b503450b1cc6408c03f3c2a935124cfba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
